### ISSUE TITLE
Brewday July 2020

### ISSUE THREAD

**Issue by c7h** [nerdkiez/recipes#8]
Hey Fellow @nerdkiez/core-brewers !
We are planning a new brewday in June. 

Here's a ToDo List of things we need to plan:

- [x] Decide for recipe.
- [x] Organize ingredients.
- [x] Organize missing equipment. 
- [x] Check gas bottle.

Feel free to update this issue as needed.

**Comment by ChrisWeissmann** [comment]
What is the missing equipment?

**Comment by s7e** [comment]
Was wollen wir denn jetzt brauen?
Mein Vorschlag wäre, wie gesagt, ein Double IPA. Was meint ihr? Habt ihr andere Vorschläge?

**Comment by ChrisWeissmann** [comment]
Ja is ok fur mich. Hast du ein Rezept?

**Comment by ChrisWeissmann** [comment]
@c7h What is the missing equipment?
@s7e Du kannst hier bei [Maische malz und mehr](https://www.maischemalzundmehr.de/) mal nach nem Rezept schauen. Dann bestell mers beim Mashpit vor

**Comment by s7e** [comment]
https://www.maischemalzundmehr.de/index.php?id=1135&inhaltmitte=rezept&suche_sorte=India%20Pale%20Ale%20(NEIPA)

Das hört sich imo ganz gut an.
Allerdings müsste 2 mal Stopfhopfen hinzugegeben werden. Einmal 24h nach Gärungsbeginn und einmal 5 Tage nach Gärungsbeginn.
@c7h Würdest du das hinkriegen?

**Comment by ChrisWeissmann** [comment]
Bei 24h bin ich noch da. Aber nach 5 Tagen müssen wir zwei halt @ChrisWeissmann und @s7e Telefon terror beim @c7h machen

**Comment by s7e** [comment]
:-D
Das Mashpit scheint alles außer den Nelson Sauvin zu haben. Aber da kann man eventuell Hallertauer Blanc als Alternative verwenden, der soll in etwa die gleichen Eigenschaften haben.
Über das mysteriöse fehlende Equipment wissen wir jetzt leider immer noch nichts :-(

**Comment by c7h** [comment]
> Über das mysteriöse fehlende Equipment wissen wir jetzt leider immer noch nichts :-(

Ich hab gerade nochmal gecheckt und es fehlt lediglich das Refraktometer. Das hol ich mir aber noch ab. Der Würzekühler wäre wieder ganz praktisch. 

> @c7h Würdest du das hinkriegen?

Logo!



Das Rezept würde ich noch etwas anpassen, da wir mit unserem Prozess erfahrungsgemäß ohnehin auf eine höhere Gravity kommen. Das Bier könnte dann etwas "schwer" werden. Ich schlage vor, den Nachguss etwas großzügiger auszulegen.

**Comment by ChrisWeissmann** [comment]
Wäre ok mit beiden Anpassungen, versteh sie aber das mit der gravity nicht ganz. Wir müssen unsere Würze quasi verdünnen mit mehr nachguss da user Läuter verfahren nicht so effektiv ist?
Sollten aber nochmal überlegen wieviel platz im topf is, net des wir beim Nachguss übertreiben und dann langt der Topf net.

**Comment by ChrisWeissmann** [comment]
Brew day in progress. Closing.
